### ISSUE TITLE
`java.lang.NullPointerException: Ticking entity`

### ISSUE THREAD

**Issue by Bricklou** [nivoridocs/strawgolem#15]
Hi,
my friend have a modded server in 1.14.4 and have some issues while using this mod:

Here the crash logs:
```log
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 8/4/21 12:28 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.util.math.Vec3i.func_218139_n(SourceFile:208) ~[?:?] {re:classloading}
	at com.commodorethrawn.strawgolem.entity.ai.GolemTetherGoal.getTetherDistance(GolemTetherGoal.java:28) ~[?:1.14.4-1.9] {re:classloading}
	at com.commodorethrawn.strawgolem.entity.ai.GolemTetherGoal.func_75250_a(GolemTetherGoal.java:40) ~[?:1.14.4-1.9] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75250_a(SourceFile:22) ~[?:?] {re:classloading}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_302] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_302] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_302] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_302] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_302] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_302] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_302] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_302] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_302] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_302] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_302] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_302] {}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:69) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:590) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2187) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:460) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2033) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587) ~[?:?] {re:classloading,xf:fml:immersiveengineering:IE block update callback,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:684) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394) ~[?:?] {re:classloading,xf:fml:immersiveengineering:IE block update callback,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:766) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.util.math.Vec3i.func_218139_n(SourceFile:208)
	at com.commodorethrawn.strawgolem.entity.ai.GolemTetherGoal.getTetherDistance(GolemTetherGoal.java:28)
	at com.commodorethrawn.strawgolem.entity.ai.GolemTetherGoal.func_75250_a(GolemTetherGoal.java:40)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75250_a(SourceFile:22)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:69)
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:590)
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2187)
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:460)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2033)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587)

-- Entity being ticked --
Details:
	Entity Type: strawgolem:strawgolem (com.commodorethrawn.strawgolem.entity.EntityStrawGolem)
	Entity ID: 426
	Entity Name: Straw Golem
	Entity's Exact location: -6.90, 72.00, 72.50
	Entity's Block location: World: (-7,72,72), Chunk: (at 9,4,8 in -1,4; contains blocks -16,0,64 to -1,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.03, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:684)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394)

-- Affected level --
Details:
	All players: 2 total; [ServerPlayerEntity['AnthoSkilart'/326, l='world', x=-11.81, y=72.00, z=72.69], ServerPlayerEntity['Cochinii'/368, l='world', x=-8.32, y=72.00, z=74.44]]
	Chunk stats: ServerChunkCache: 2200
	Level dimension: DimensionType{minecraft:overworld}
	Level name: world
	Level seed: 2847
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (16,63,-96), Chunk: (at 0,3,0 in 1,-6; contains blocks 16,0,-96 to 31,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 189780 game time, 8160 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 13868 (now: false), thunder time: 103450 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:766)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Linux (amd64) version 5.4.0-72-generic
	Java Version: 1.8.0_302, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1317501928 bytes (1256 MB) / 2207776768 bytes (2105 MB) up to 2207776768 bytes (2105 MB)
	CPUs: 3
	JVM Flags: 3 total; -XX:MaxMetaspaceSize=200M -Xmx2300M -Xms1150M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge.jar object_holder_definalize PLUGINSERVICE 
		/forge.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.5-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge.jar capability_inject_definalize PLUGINSERVICE 
		/forge.jar runtimedistcleaner PLUGINSERVICE 
		/forge.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.23
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		forge-1.14.4-28.2.23-server.jar Minecraft {minecraft@1.14.4 DONE}
		mowziesmobs-1.5.12.jar Mowzie's Mobs {mowziesmobs@1.5.12 DONE}
		illagers_plus-2.1.jar Illagers+ {illagers_plus@2.1(BETA) DONE}
		forge-1.14.4-28.2.23-universal.jar Forge {forge@28.2.23 DONE}
		strawgolem-1.14.4-1.9.jar Straw Golem {strawgolem@1.14.4-1.9 DONE}
		ImmersiveEngineering-1.14.4-4.0.0-116.jar Immersive Engineering {immersiveengineering@1.14.4-4.0.0-116 DONE}
		ExtraSpace 1.0.5 1.14.4.jar extraspace {extraspace@1.0.5 DONE}
		citadel-1.0.4-1.14.4.jar Citadel {citadel@1.0.4 DONE}
		rats-4.1.1-1.14.4.jar Rats {rats@4.1.1 DONE}
		[1.14.4] SecurityCraft v1.8.22.2.jar SecurityCraft {securitycraft@v1.8.22.2 DONE}
		OreExcavation-1.6.147.jar Ore Excavation {oreexcavation@NONE DONE}
		jei-1.14.4-6.0.1.30.jar Just Enough Items {jei@6.0.1.30 DONE}
	Player Count: 2 / 50; [ServerPlayerEntity['AnthoSkilart'/326, l='world', x=-11.81, y=72.00, z=72.69], ServerPlayerEntity['Cochinii'/368, l='world', x=-8.32, y=72.00, z=74.44]]
	Data Packs: vanilla, mod:citadel, mod:extraspace, mod:forge, mod:illagers_plus, mod:immersiveengineering, mod:jei, mod:mowziesmobs, mod:oreexcavation, mod:rats, mod:securitycraft, mod:strawgolem
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Bricklou** [comment]
My bad, this is for the Reborn version. I'm closing the issue
